name = "workerbot"
main = "./src/server.js"
type = "javascript"
compatibility_date="2022-05-22"

account_id = "692590628999135293"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
